{
 "title": "ECUdata",
 "time": { "from": "2018-07-14T02:09:11.195Z", "to": "2018-07-15T17:18:39.616Z" },
 "panels": [
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  supplyvoltage\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Cylinder Contribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  cylcontrib1,\n  cylcontrib2,\n  cylcontrib3,\n  cylcontrib4\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  gear\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  roadspeed\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Fuel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  fuelflow,\n  fuelmass,\n  fp_abs / 1000.0 AS fuelpressure\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  throttle\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Cooling Fan Relay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  coolingfan_primary\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "MAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  map\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Coolant Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  coolanttemp\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  enginespeed\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n date + duration * INTERVAL '1s' AS time,\n  airtemp\nFROM\n  vehicledata\nWHERE\n  $__timeFilter(date)\nORDER BY\n  time\n"
    }
   ]
  }
 ]
}